name: Deploy to GitHub Pages

on:
    push:
        branches:
          - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Access Secret
          run: echo "The secret is ${{ secrets.REACT_APP_API_KEY }}"
          env:
            REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@4.0.0
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
            BRANCH: gh-pages
            FOLDER: build
